logger:
  level: "debug"
http:
  host: "0.0.0.0"
  port: 3000
  readTimeout: 1s
  writeTimeout: 1s
grpc:
  host: "0.0.0.0"
  port: 50051
  connectTimeout: 1s
db:
  dsn: "postgres://postgres:postgres@0.0.0.0:5432/otus_golang_hw"
  migrationsDir: "./migrations/"
rmq:
  host: "0.0.0.0"
  port: "5672"
  login: "guest"
  password: "guest"
app:
  scheduler:
    period: 10s
    retentionPeriod: 8760h
    queue: "calendar_events"
storage: "db"
